fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: fr
            editor: ckeditor
            theme: smoothness
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/image
                        show_hidden: false
                        upload_allow: ['image/png', 'image/jpeg', 'image/jpg', 'application/pdf']
                        upload_max_size: 10M
