<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGBWMTVS\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGBWMTVS/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGBWMTVS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGBWMTVS\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerGBWMTVS\srcApp_KernelProdContainer([
    'container.build_hash' => 'GBWMTVS',
    'container.build_id' => '9ed2b51d',
    'container.build_time' => 1595015014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGBWMTVS');
