<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHaiGoHW\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHaiGoHW/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHaiGoHW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHaiGoHW\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerHaiGoHW\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'HaiGoHW',
    'container.build_id' => 'b015246d',
    'container.build_time' => 1594488574,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHaiGoHW');
