<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxop7A7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxop7A7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxop7A7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxop7A7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTxop7A7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Txop7A7',
    'container.build_id' => '881e329c',
    'container.build_time' => 1596073893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxop7A7');
