<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOmRvtiH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOmRvtiH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOmRvtiH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOmRvtiH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOmRvtiH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OmRvtiH',
    'container.build_id' => '2823e943',
    'container.build_time' => 1597781480,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOmRvtiH');
