<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3l9Nnvm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3l9Nnvm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3l9Nnvm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3l9Nnvm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3l9Nnvm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3l9Nnvm',
    'container.build_id' => '9e61efc9',
    'container.build_time' => 1596382082,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3l9Nnvm');
