<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articles extends \App\Entity\Articles implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'content1', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'img1', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'img2', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'img3', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'category'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'content1', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'img1', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'img2', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'img3', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'category'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Articles $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent1', []);

        return parent::getContent1();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent1(string $content1): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent1', [$content1]);

        return parent::setContent1($content1);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg1', []);

        return parent::getImg1();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg1(string $img1): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg1', [$img1]);

        return parent::setImg1($img1);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg2', []);

        return parent::getImg2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg2(?string $img2): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg2', [$img2]);

        return parent::setImg2($img2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg3', []);

        return parent::getImg3();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg3(?string $img3): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg3', [$img3]);

        return parent::setImg3($img3);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(string $created_at): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(string $category): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

}
